// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvGaijRJddUv32FPInr_SwJi-dUbzDgbQ',
    appId: '1:476995953521:web:39196a667e6dd284934cd0',
    messagingSenderId: '476995953521',
    projectId: 'ribercerra',
    authDomain: 'ribercerra.firebaseapp.com',
    storageBucket: 'ribercerra.appspot.com',
    measurementId: 'G-K22ZPFMSRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHjd2MZttGTrGr8G2Mt_HGZ8ypZUiJwk0',
    appId: '1:476995953521:android:beca7fb6a1819c6b934cd0',
    messagingSenderId: '476995953521',
    projectId: 'ribercerra',
    storageBucket: 'ribercerra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2PrMB8nRcHbSMLcnF37o2BTIWZLLl-fo',
    appId: '1:476995953521:ios:580249a5177da57f934cd0',
    messagingSenderId: '476995953521',
    projectId: 'ribercerra',
    storageBucket: 'ribercerra.appspot.com',
    iosClientId: '476995953521-1ivf2u4m1s3kp33ot4vkhgv0gh6oa9m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.riberCerra',
  );
}
